// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromoCode.Models;

#nullable disable

namespace PromoCode.Migrations
{
    [DbContext(typeof(DBPromoCode))]
    [Migration("20221215043330_addKeystring")]
    partial class addKeystring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PromoCode.Models.LoginViewModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("loginViewModels");
                });

            modelBuilder.Entity("PromoCode.Models.PromoCode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("activationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("activaton")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dataTimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("extradition")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("extraditionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("keySessions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("PromoCode");
                });
#pragma warning restore 612, 618
        }
    }
}
